services:
  db:
    image: postgis/postgis:14-3.4 # Postgres + PostGIS image
    container_name: city-issue-tracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    #restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: city-issue-tracker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbitmq_pass_123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    #restart: unless-stopped

volumes:
  rabbitmq_data:
