services:
  db:
    image: postgis/postgis:14-3.4 # Postgres + PostGIS image
    container_name: citizen-tracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    #restart: unless-stopped
#volumes:
#  postgres_data:
